openapi: 3.0.0

info:
    title: httpbin-manifest
    description: httpbin ip requester info
    version: "1.0.0"

servers:
    - url: https://httpbin.org/

paths:
    /headers:
        get: 
            operationId: httpbintest
            summary: Return the ip requester information based on the incoming request.
            responses:
                200:
                    description: Successful authentication.
                401:
                    description: Unsuccessful authentication.
